spring.application.name=vagaManager

spring.datasource.url=jdbc:postgresql://localhost:5432/vaga_manager_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update


# security
security.secret.token=VAGAMANAGER_@123#
security.secret.token.candidate=VAGAMANAGER_CAND_@123#