spring.application.name=vagaManager

spring.datasource.url=jdbc:postgresql://localhost:5432/vaga_manager_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update